version: '3'
  
silent: true

tasks:
  default:
    aliases:
      - list
    desc: List all tasks
    cmd: task -l

  build:
    desc: Build the project
    cmds: 
      - cp .env.example .env
      - docker compose build
      - docker compose run -it --rm cmake bash -c "cd /root/rse/goal && unzip -o GOAL-20200506-with-API.zip && java -XX:MaxHeapSize=8G -XX:MaxRAM=8G -version"
  
  run:
    desc: "Run the project. The first parameter is the LTL formula, and the second and subsequent parameters are response events."
    cmds: 
      - docker compose run -it --rm cmake bash -c "cd /root/rse/build && cmake .. && make && ./rse {{.CLI_ARGS}}"

  clean:
    desc: delete build directory
    cmds:
      - docker compose run -it --rm cmake bash -c "find /root/rse/build -type f | xargs rm -f && rm -rf /root/rse/build/CMakeFiles && touch /root/rse/build/.gitkeep"
      - echo 'cleaned'

  change:
    desc: change the complement algorithm (default modifiedsafra)
    cmds:
      - docker compose run -it --rm cmake bash -c "cd /root/rse/src && sed -i 's/complement -m [a-zA-Z0-9_-]*/complement -m {{.CLI_ARGS}}/' script.sh"

  dot2png:
    desc: convert dot file to png
    cmds:
      - docker compose run -it --rm cmake bash -c "cd /root/rse/build && dot -Tpng -o automaton.png automaton.dot"